<?xml version="1.0"?>

<!DOCTYPE Users [
  <!ELEMENT Users (User*)>
  <!ELEMENT User (Team, Country, Project, RegDate, AvgScore, AllScore)>
  <!ATTLIST User ID ID #REQUIRED 
	    UserName CDATA #REQUIRED>
  <!ELEMENT Team (#PCDATA)>
  <!ELEMENT Country (#PCDATA)>
  <!ELEMENT Project (#PCDATA)>
  <!ELEMENT RegDate (#PCDATA)>
  <!ELEMENT AvgScore (#PCDATA)>
  <!ELEMENT AllScore (#PCDATA)>
]>

<Users>
  <User ID="User1" UserName="delitePS3">
    <Team>NCSU Wolfpack</Team>
    <Country>GERMANY</Country>
    <Project>Climate Prediction</Project>
    <RegDate>2006/7/29</RegDate>
    <AvgScore>760.745</AvgScore>
    <AllScore>5980949</AllScore>
  </User>
  <User ID="User2" UserName="beredon">
    <?instruction targetID="Russian federation"?>
    <Team>CHIP Indonesia Folding Fellow</Team>
    <Country>UNITED KINGDOM</Country>
    <Project>Reversi</Project>
    <RegDate>2003/12/26</RegDate>
    <AvgScore>326.174</AvgScore>
    <AllScore>6602121</AllScore>
  </User>
  <User ID="User3" UserName="DIPthong!">
    <Team>[H]ardOCP</Team>
    <Country>CANADA</Country>
    <Project>Sudoku project</Project>
    <RegDate>2005/11/17</RegDate>
    <AvgScore>459.812</AvgScore>
    <AllScore>5405140</AllScore>
  </User>
  <!-- example of comment -->
  <User ID="User4" UserName="T1212I">
    <Team>folding@evga</Team>
    <Country>FRANCE</Country>
    <Project>World Community Grid</Project>
    <RegDate>1999/2/16</RegDate>
    <AvgScore>794.867</AvgScore>
    <AllScore>3900425</AllScore>
  </User>
  <User ID="User5" UserName="nkh33">
    <Team>NCIX.com Forum Folding Team</Team>
    <Country>FRANCE</Country>
    <Project>QMC@Home</Project>
    <RegDate>2007/9/20</RegDate>
    <AvgScore>290.230</AvgScore>
    <AllScore>9211405</AllScore>
  </User>
  <User ID="User6" UserName="google133770995893900">
    <Team>Alliance Francophone</Team>
    <Country>FRANCE</Country>
    <Project>RSA Lattice Siever (2.0)</Project>
    <RegDate>2003/4/2</RegDate>
    <AvgScore>878.949</AvgScore>
    <AllScore>6381233</AllScore>
  </User>
  <User ID="User7" UserName="Denzil_(XPS)">
    <Team>p2p-community</Team>
    <Country>UNITED STATES</Country>
    <Project>World Community Grid</Project>
    <RegDate>2006/6/19</RegDate>
    <AvgScore>253.063</AvgScore>
    <AllScore>1807714</AllScore>
  </User>
  <User ID="User8" UserName="ZK148P15">
    <Team>General [M]ayhem</Team>
    <Country>JAPAN</Country>
    <Project>World Community Grid</Project>
    <RegDate>2003/4/24</RegDate>
    <AvgScore>21.733</AvgScore>
    <AllScore>5014153</AllScore>
  </User>
  <User ID="User9" UserName="neo1211">
    <Team>Team MacOS X</Team>
    <Country>UNITED KINGDOM</Country>
    <Project>NQueens Project</Project>
    <RegDate>2002/8/18</RegDate>
    <AvgScore>160.708</AvgScore>
    <AllScore>7535349</AllScore>
  </User>
  <User ID="User10" UserName="JLBauermeister">
    <Team>MacAddict4Life</Team>
    <Country>ROMANIA</Country>
    <Project>SIMAP</Project>
    <RegDate>2003/11/24</RegDate>
    <AvgScore>247.674</AvgScore>
    <AllScore>7250681</AllScore>
  </User>
  <User ID="User11" UserName="MrFork">
    <Team>SilentPCReview Folding@Home</Team>
    <Country>UNITED KINGDOM</Country>
    <Project>The Lattice Project</Project>
    <RegDate>2000/6/18</RegDate>
    <AvgScore>44.989</AvgScore>
    <AllScore>3221587</AllScore>
  </User>
  <User ID="User12" UserName="Yaron_Livne_-_Ly362">
    <Team>HKEPC</Team>
    <Country>THAILAND</Country>
    <Project>The Lattice Project</Project>
    <RegDate>2009/5/25</RegDate>
    <AvgScore>838.291</AvgScore>
    <AllScore>6097164</AllScore>
  </User>
  <User ID="User13" UserName="ChrisandStania">
    <Team>The Longevity Meme</Team>
    <Country>GERMANY</Country>
    <Project>MilkyWay@home</Project>
    <RegDate>2002/6/22</RegDate>
    <AvgScore>325.496</AvgScore>
    <AllScore>3102198</AllScore>
  </User>
  <User ID="User14" UserName="RooR">
    <Team>SpeedGuide.net</Team>
    <Country>INDIA</Country>
    <Project>LHC@Home</Project>
    <RegDate>2000/3/17</RegDate>
    <AvgScore>651.540</AvgScore>
    <AllScore>4365035</AllScore>
  </User>
  <User ID="User15" UserName="Noodles">
    <Team>PC Perspective Folding Frogs (734)</Team>
    <Country>UNITED STATES</Country>
    <Project>Spinhenge@home</Project>
    <RegDate>2009/4/11</RegDate>
    <AvgScore>887.677</AvgScore>
    <AllScore>2789422</AllScore>
  </User>
  <User ID="User16" UserName="mav">
    <Team>Hardware.no</Team>
    <Country>UNITED STATES</Country>
    <Project>Magnetism@home</Project>
    <RegDate>2003/7/17</RegDate>
    <AvgScore>710.970</AvgScore>
    <AllScore>2277374</AllScore>
  </User>
  <User ID="User17" UserName="Traxan">
    <Team>www.overclockers.com</Team>
    <Country>SINGAPORE</Country>
    <Project>Einstein@Home</Project>
    <RegDate>1999/4/25</RegDate>
    <AvgScore>350.050</AvgScore>
    <AllScore>6773254</AllScore>
  </User>
  <User ID="User18" UserName="tablerrocker">
    <Team>EOC Folding@Home Team</Team>
    <Country>GERMANY</Country>
    <Project>World Community Grid</Project>
    <RegDate>2005/6/17</RegDate>
    <AvgScore>472.327</AvgScore>
    <AllScore>8844740</AllScore>
  </User>
  <User ID="User19" UserName="Katarina">
    <Team>folding@evga</Team>
    <Country>BELGIUM</Country>
    <Project>Einstein@Home</Project>
    <RegDate>2007/12/8</RegDate>
    <AvgScore>84.179</AvgScore>
    <AllScore>7957763</AllScore>
  </User>
  <User ID="User20" UserName="leo">
    <Team>[H]ardOCP</Team>
    <Country>IRELAND</Country>
    <Project>SETI@Home</Project>
    <RegDate>1998/12/7</RegDate>
    <AvgScore>373.795</AvgScore>
    <AllScore>1693704</AllScore>
  </User>
  <User ID="User21" UserName="CheezyRadio">
    <Team>Folding@Malaysia</Team>
    <Country>ROMANIA</Country>
    <Project>BURP</Project>
    <RegDate>2004/7/19</RegDate>
    <AvgScore>334.352</AvgScore>
    <AllScore>517555</AllScore>
  </User>
  <User ID="User22" UserName="edahand">
    <Team>Team 2ch</Team>
    <Country>AUSTRALIA</Country>
    <Project>Climate Prediction</Project>
    <RegDate>2007/12/20</RegDate>
    <AvgScore>645.648</AvgScore>
    <AllScore>6389191</AllScore>
  </User>
  <User ID="User23" UserName="jagadish_bojja">
    <Team>PlayStation.com Forums Team</Team>
    <Country>CHINA</Country>
    <Project>World Community Grid</Project>
    <RegDate>2010/1/15</RegDate>
    <AvgScore>841.338</AvgScore>
    <AllScore>3286661</AllScore>
  </User>
  <User ID="User24" UserName="Subbu_Ilan">
    <Team>GruntvillE.CoM</Team>
    <Country>UNITED KINGDOM</Country>
    <Project>GPUGRID</Project>
    <RegDate>2007/3/10</RegDate>
    <AvgScore>349.447</AvgScore>
    <AllScore>8187465</AllScore>
  </User>
  <User ID="User25" UserName="team_drift">
    <Team>Toms Hardware Guide Community</Team>
    <Country>INDIA</Country>
    <Project>World Community Grid</Project>
    <RegDate>2005/5/28</RegDate>
    <AvgScore>388.035</AvgScore>
    <AllScore>6747513</AllScore>
  </User>
  <User ID="User26" UserName="n9yv">
    <Team>MSI HQ Red Rockets</Team>
    <Country>JAPAN</Country>
    <Project>SIMAP</Project>
    <RegDate>1998/5/10</RegDate>
    <AvgScore>450.844</AvgScore>
    <AllScore>7649214</AllScore>
  </User>
  <User ID="User27" UserName="Gaasch,Christian">
    <Team>DL.TV</Team>
    <Country>ISRAEL</Country>
    <Project>SETI@Home</Project>
    <RegDate>2005/9/7</RegDate>
    <AvgScore>685.526</AvgScore>
    <AllScore>4108077</AllScore>
  </User>
  <User ID="User28" UserName="michalpoland">
    <Team>Vietnam Global Team</Team>
    <Country>ARGENTINA</Country>
    <Project>DistrRTgen</Project>
    <RegDate>2008/5/5</RegDate>
    <AvgScore>481.426</AvgScore>
    <AllScore>8224912</AllScore>
  </User>
  <User ID="User29" UserName="FUNKANICA">
    <Team>Toms Hardware Guide Community</Team>
    <Country>UNITED STATES</Country>
    <Project>ABC@home</Project>
    <RegDate>1998/7/11</RegDate>
    <AvgScore>51.122</AvgScore>
    <AllScore>9987585</AllScore>
  </User>
  <User ID="User30" UserName="Halite">
    <Team>Maximum PC Magazine</Team>
    <Country>MALAYSIA</Country>
    <Project>World Community Grid</Project>
    <RegDate>2005/2/4</RegDate>
    <AvgScore>418.067</AvgScore>
    <AllScore>2310863</AllScore>
  </User>
  <User ID="User31" UserName="kheise">
    <Team>DevFolding</Team>
    <Country>VENEZUELA</Country>
    <Project>BOINC combined</Project>
    <RegDate>2000/10/1</RegDate>
    <AvgScore>265.284</AvgScore>
    <AllScore>633723</AllScore>
  </User>
  <User ID="User32" UserName="google188657702937049">
    <Team>Hewlett Packard</Team>
    <Country>SWEDEN</Country>
    <Project>Reversi</Project>
    <RegDate>2000/8/24</RegDate>
    <AvgScore>722.775</AvgScore>
    <AllScore>2096569</AllScore>
  </User>
  <User ID="User33" UserName="JDS_IMED_LAB_2">
    <Team>Folding@SweClockers.com</Team>
    <Country>INDIA</Country>
    <Project>SETI@Home</Project>
    <RegDate>1999/7/18</RegDate>
    <AvgScore>773.934</AvgScore>
    <AllScore>5935326</AllScore>
  </User>
  <User ID="User34" UserName="google124761236597309">
    <Team>Pleasuredome Community</Team>
    <Country>GERMANY</Country>
    <Project>LHC@Home</Project>
    <RegDate>1998/1/19</RegDate>
    <AvgScore>265.666</AvgScore>
    <AllScore>1025026</AllScore>
  </User>
  <User ID="User35" UserName="Salanki">
    <Team>[H]ardOCP</Team>
    <Country>SINGAPORE</Country>
    <Project>SETI@Home</Project>
    <RegDate>2002/10/29</RegDate>
    <AvgScore>229.914</AvgScore>
    <AllScore>4875128</AllScore>
  </User>
  <User ID="User36" UserName="Rolandas">
    <Team>Team RSF</Team>
    <Country>SLOVAKIA</Country>
    <Project>SETI@Home</Project>
    <RegDate>2007/11/28</RegDate>
    <AvgScore>954.793</AvgScore>
    <AllScore>530842</AllScore>
  </User>
  <User ID="User37" UserName="Splintre">
    <Team>Maximum PC Magazine</Team>
    <Country>SWEDEN</Country>
    <Project>Malaria Control</Project>
    <RegDate>2003/5/7</RegDate>
    <AvgScore>619.990</AvgScore>
    <AllScore>5842304</AllScore>
  </User>
  <User ID="User38" UserName="google173553857100296">
    <Team>Overclockers Club</Team>
    <Country>SWEDEN</Country>
    <Project>Ramsey@Home</Project>
    <RegDate>2006/9/10</RegDate>
    <AvgScore>414.990</AvgScore>
    <AllScore>147227</AllScore>
  </User>
  <User ID="User39" UserName="pike">
    <Team>PC Magazine Greek Edition</Team>
    <Country>KOREA, REPUBLIC OF</Country>
    <Project>Chess960@Home</Project>
    <RegDate>2001/5/26</RegDate>
    <AvgScore>721.291</AvgScore>
    <AllScore>9779725</AllScore>
  </User>
  <User ID="User40" UserName="toka">
    <Team>whoopass</Team>
    <Country>FRANCE</Country>
    <Project>ABC@home</Project>
    <RegDate>2009/2/17</RegDate>
    <AvgScore>713.635</AvgScore>
    <AllScore>5706657</AllScore>
  </User>
  <User ID="User41" UserName="JKsniper">
    <Team>TechPowerup!</Team>
    <Country>HONG KONG</Country>
    <Project>Einstein@Home</Project>
    <RegDate>1998/9/28</RegDate>
    <AvgScore>735.624</AvgScore>
    <AllScore>4603369</AllScore>
  </User>
  <User ID="User42" UserName="crunchips">
    <Team>Maximum PC Magazine</Team>
    <Country>UNITED STATES</Country>
    <Project>DistrRTgen</Project>
    <RegDate>2005/7/2</RegDate>
    <AvgScore>935.027</AvgScore>
    <AllScore>3793850</AllScore>
  </User>
  <User ID="User43" UserName="Arkaline">
    <Team>NCIX.com Forum Folding Team</Team>
    <Country>FRANCE</Country>
    <Project>AlmereGrid Boinc Grid</Project>
    <RegDate>2003/11/19</RegDate>
    <AvgScore>530.201</AvgScore>
    <AllScore>802441</AllScore>
  </User>
  <User ID="User44" UserName="hej">
    <Team>TechPowerup!</Team>
    <Country>UNITED STATES</Country>
    <Project>Spinhenge@home</Project>
    <RegDate>1998/12/5</RegDate>
    <AvgScore>817.353</AvgScore>
    <AllScore>8989098</AllScore>
  </User>
  <User ID="User45" UserName="wuqiang">
    <Team>2ch@PS3</Team>
    <Country>TURKEY</Country>
    <Project>Einstein@Home</Project>
    <RegDate>2000/7/28</RegDate>
    <AvgScore>964.188</AvgScore>
    <AllScore>5815440</AllScore>
  </User>
  <User ID="User46" UserName="scleone1987">
    <Team>www.overclockers.com</Team>
    <Country>SINGAPORE</Country>
    <Project>RNA World</Project>
    <RegDate>2008/6/14</RegDate>
    <AvgScore>480.666</AvgScore>
    <AllScore>1060301</AllScore>
  </User>
  <User ID="User47" UserName="google125037256912675">
    <Team>Portugal@Folding</Team>
    <Country>INDIA</Country>
    <Project>Seasonal Attribution</Project>
    <RegDate>2003/3/13</RegDate>
    <AvgScore>41.459</AvgScore>
    <AllScore>1336007</AllScore>
  </User>
  <User ID="User48" UserName="Xquad">
    <Team>[H]ardOCP</Team>
    <Country>ROMANIA</Country>
    <Project>SETI@Home</Project>
    <RegDate>2007/5/22</RegDate>
    <AvgScore>481.876</AvgScore>
    <AllScore>1113323</AllScore>
  </User>
  <User ID="User49" UserName="mackj">
    <Team>Maximum PC Magazine</Team>
    <Country>POLAND</Country>
    <Project>LHC@Home</Project>
    <RegDate>2006/5/7</RegDate>
    <AvgScore>957.956</AvgScore>
    <AllScore>5444060</AllScore>
  </User>
  <User ID="User50" UserName="DecimalCat">
    <Team>[H]ardOCP</Team>
    <Country>GERMANY</Country>
    <Project>RNA World</Project>
    <RegDate>2007/5/25</RegDate>
    <AvgScore>452.881</AvgScore>
    <AllScore>9581537</AllScore>
  </User>
  <User ID="User51" UserName="muttley383">
    <Team>Vietnam Global Team</Team>
    <Country>SOUTH AFRICA</Country>
    <Project>LHC@Home</Project>
    <RegDate>2004/12/14</RegDate>
    <AvgScore>921.360</AvgScore>
    <AllScore>1713807</AllScore>
  </User>
  <User ID="User52" UserName="FamiliaArochi">
    <Team>PlanetAMD64</Team>
    <Country>GERMANY</Country>
    <Project>Rosetta@Home</Project>
    <RegDate>1998/5/10</RegDate>
    <AvgScore>836.896</AvgScore>
    <AllScore>3586832</AllScore>
  </User>
  <User ID="User53" UserName="punisher_ds">
    <Team>TechPowerup!</Team>
    <Country>COLOMBIA</Country>
    <Project>Einstein@Home</Project>
    <RegDate>2003/6/21</RegDate>
    <AvgScore>324.935</AvgScore>
    <AllScore>9790898</AllScore>
  </User>
  <User ID="User54" UserName="Smaskis">
    <Team>Hardware Canucks Forum</Team>
    <Country>UNITED KINGDOM</Country>
    <Project>NFS@Home</Project>
    <RegDate>2009/4/14</RegDate>
    <AvgScore>531.002</AvgScore>
    <AllScore>9151344</AllScore>
  </User>
  <User ID="User55" UserName="nbvincent">
    <Team>Overclock.net</Team>
    <Country>AUSTRIA</Country>
    <Project>RALPH@Home</Project>
    <RegDate>2009/9/6</RegDate>
    <AvgScore>69.968</AvgScore>
    <AllScore>502278</AllScore>
  </User>
  <User ID="User56" UserName="Chung">
    <Team>The Folding Wolves</Team>
    <Country>UNITED STATES</Country>
    <Project>Spinhenge@home</Project>
    <RegDate>1999/12/1</RegDate>
    <AvgScore>961.732</AvgScore>
    <AllScore>1394387</AllScore>
  </User>
  <User ID="User57" UserName="csmerlin">
    <Team>ClubLexus</Team>
    <Country>GERMANY</Country>
    <Project>World Community Grid</Project>
    <RegDate>2004/6/28</RegDate>
    <AvgScore>725.035</AvgScore>
    <AllScore>597147</AllScore>
  </User>
  <User ID="User58" UserName="google131623841965323">
    <Team>www.overclockers.com</Team>
    <Country>INDIA</Country>
    <Project>POEM@HOME</Project>
    <RegDate>1999/8/8</RegDate>
    <AvgScore>19.606</AvgScore>
    <AllScore>3573339</AllScore>
  </User>
  <User ID="User59" UserName="PH_GRZES">
    <Team>PC Perspective Folding Frogs (734)</Team>
    <Country>GREECE</Country>
    <Project>World Community Grid</Project>
    <RegDate>1999/3/14</RegDate>
    <AvgScore>429.837</AvgScore>
    <AllScore>7153026</AllScore>
  </User>
  <User ID="User60" UserName="CMOS">
    <Team>Team RSF</Team>
    <Country>TAIWAN</Country>
    <Project>SIMAP</Project>
    <RegDate>2005/5/10</RegDate>
    <AvgScore>301.705</AvgScore>
    <AllScore>3449334</AllScore>
  </User>
  <User ID="User61" UserName="vista">
    <Team>Team 2ch</Team>
    <Country>CANADA</Country>
    <Project>Proteins@home</Project>
    <RegDate>2002/3/9</RegDate>
    <AvgScore>249.647</AvgScore>
    <AllScore>9956751</AllScore>
  </User>
  <User ID="User62" UserName="wp4">
    <Team>Legit Reviews</Team>
    <Country>CHILE</Country>
    <Project>SIMAP</Project>
    <RegDate>2003/4/11</RegDate>
    <AvgScore>554.410</AvgScore>
    <AllScore>7444188</AllScore>
  </User>
  <User ID="User63" UserName="Teh_snacksus">
    <Team>ClubLexus</Team>
    <Country>UNITED STATES</Country>
    <Project>ABC@home</Project>
    <RegDate>2001/7/9</RegDate>
    <AvgScore>938.814</AvgScore>
    <AllScore>7179013</AllScore>
  </User>
  <User ID="User64" UserName="SulSeeker">
    <Team>Hardware.no</Team>
    <Country>CHILE</Country>
    <Project>QMC@Home</Project>
    <RegDate>2004/10/1</RegDate>
    <AvgScore>136.395</AvgScore>
    <AllScore>1801895</AllScore>
  </User>
  <User ID="User65" UserName="google276332961172798">
    <Team>folding@evga</Team>
    <Country>NORWAY</Country>
    <Project>RSA Lattice Siever (2.0)</Project>
    <RegDate>1999/8/2</RegDate>
    <AvgScore>108.308</AvgScore>
    <AllScore>8516766</AllScore>
  </User>
  <User ID="User66" UserName="TeamHayes">
    <Team>Macrumors.com - Team Folding</Team>
    <Country>MALAYSIA</Country>
    <Project>Rosetta@Home</Project>
    <RegDate>2004/9/7</RegDate>
    <AvgScore>272.043</AvgScore>
    <AllScore>9848964</AllScore>
  </User>
  <User ID="User67" UserName="Anunakin">
    <Team>[H]ardOCP</Team>
    <Country>UKRAINE</Country>
    <Project>Einstein@Home</Project>
    <RegDate>2008/8/12</RegDate>
    <AvgScore>855.100</AvgScore>
    <AllScore>4677177</AllScore>
  </User>
  <User ID="User68" UserName="Bulvox">
    <Team>www.overclockers.com</Team>
    <Country>UNITED KINGDOM</Country>
    <Project>Climate Prediction</Project>
    <RegDate>2006/6/4</RegDate>
    <AvgScore>331.548</AvgScore>
    <AllScore>6714045</AllScore>
  </User>
  <User ID="User69" UserName="Asmodeus">
    <Team>Bjorn3D.Com</Team>
    <Country>FRANCE</Country>
    <Project>World Community Grid</Project>
    <RegDate>2000/10/27</RegDate>
    <AvgScore>962.666</AvgScore>
    <AllScore>7411321</AllScore>
  </User>
  <User ID="User70" UserName="MrBill">
    <Team>TechIMO</Team>
    <Country>SLOVENIA</Country>
    <Project>Chess960@Home</Project>
    <RegDate>2008/11/7</RegDate>
    <AvgScore>281.495</AvgScore>
    <AllScore>348298</AllScore>
  </User>
  <User ID="User71" UserName="ysong_#2">
    <Team>Team 2ch</Team>
    <Country>JAPAN</Country>
    <Project>Malaria Control</Project>
    <RegDate>2009/4/5</RegDate>
    <AvgScore>506.529</AvgScore>
    <AllScore>9286953</AllScore>
  </User>
  <User ID="User72" UserName="g33kevolved">
    <Team>the motherboards.org team</Team>
    <Country>UNITED STATES</Country>
    <Project>MilkyWay@home</Project>
    <RegDate>2004/3/2</RegDate>
    <AvgScore>126.005</AvgScore>
    <AllScore>5188314</AllScore>
  </User>
  <User ID="User73" UserName="maxamd400">
    <Team>The Folding Wolves</Team>
    <Country>GREECE</Country>
    <Project>ABC@home</Project>
    <RegDate>2002/10/27</RegDate>
    <AvgScore>294.979</AvgScore>
    <AllScore>9626470</AllScore>
  </User>
  <User ID="User74" UserName="arnaldo.melo">
    <Team>Ukraine</Team>
    <Country>AUSTRALIA</Country>
    <Project>PrimeGrid</Project>
    <RegDate>2009/5/14</RegDate>
    <AvgScore>302.774</AvgScore>
    <AllScore>9286294</AllScore>
  </User>
  <User ID="User75" UserName="tNMarklar">
    <Team>CHIP Indonesia Folding Fellow</Team>
    <Country>BULGARIA</Country>
    <Project>UCT Malaria</Project>
    <RegDate>2008/9/28</RegDate>
    <AvgScore>328.181</AvgScore>
    <AllScore>279396</AllScore>
  </User>
  <User ID="User76" UserName="google71806616099039">
    <Team>CHIP Indonesia Folding Fellow</Team>
    <Country>NETHERLANDS</Country>
    <Project>SIMAP</Project>
    <RegDate>1998/9/11</RegDate>
    <AvgScore>353.193</AvgScore>
    <AllScore>7893669</AllScore>
  </User>
  <User ID="User77" UserName="Kevin_Rice(Jaycees)">
    <Team>guru3d</Team>
    <Country>UNITED STATES</Country>
    <Project>NQueens Project</Project>
    <RegDate>2004/8/10</RegDate>
    <AvgScore>659.586</AvgScore>
    <AllScore>305589</AllScore>
  </User>
  <User ID="User78" UserName="Will-Magnus">
    <Team>folding@evga</Team>
    <Country>UNITED STATES</Country>
    <Project>SETI@Home</Project>
    <RegDate>2009/3/8</RegDate>
    <AvgScore>588.011</AvgScore>
    <AllScore>4100684</AllScore>
  </User>
  <User ID="User79" UserName="google118175144421908">
    <Team>NCSU Wolfpack</Team>
    <Country>TURKEY</Country>
    <Project>Collatz Conjecture</Project>
    <RegDate>1999/1/25</RegDate>
    <AvgScore>139.937</AvgScore>
    <AllScore>5808442</AllScore>
  </User>
  <User ID="User80" UserName="t_ohm83(PS3)">
    <Team>Pleasuredome Community</Team>
    <Country>CZECH REPUBLIC</Country>
    <Project>SETI@Home</Project>
    <RegDate>1999/7/18</RegDate>
    <AvgScore>247.311</AvgScore>
    <AllScore>5087363</AllScore>
  </User>
  <User ID="User81" UserName="lesbianic_messiah">
    <Team>[H]ardOCP</Team>
    <Country>GERMANY</Country>
    <Project>Hydrogen@Home</Project>
    <RegDate>2005/2/21</RegDate>
    <AvgScore>354.599</AvgScore>
    <AllScore>2394203</AllScore>
  </User>
  <User ID="User82" UserName="Jason_D_B">
    <Team>[H]ardOCP</Team>
    <Country>SOUTH AFRICA</Country>
    <Project>Einstein@Home</Project>
    <RegDate>2005/6/9</RegDate>
    <AvgScore>698.632</AvgScore>
    <AllScore>3870343</AllScore>
  </User>
  <User ID="User83" UserName="xi-shiz">
    <Team>folding@evga</Team>
    <Country>TURKEY</Country>
    <Project>ABC@home</Project>
    <RegDate>2006/5/1</RegDate>
    <AvgScore>744.413</AvgScore>
    <AllScore>9736308</AllScore>
  </User>
  <User ID="User84" UserName="IKEGAMI">
    <Team>MSI HQ Red Rockets</Team>
    <Country>SLOVENIA</Country>
    <Project>PrimeGrid</Project>
    <RegDate>1999/9/22</RegDate>
    <AvgScore>372.865</AvgScore>
    <AllScore>5573403</AllScore>
  </User>
  <User ID="User85" UserName="EFG">
    <Team>Folding@SweClockers.com</Team>
    <Country>SPAIN</Country>
    <Project>RNA World</Project>
    <RegDate>2004/10/25</RegDate>
    <AvgScore>766.169</AvgScore>
    <AllScore>981470</AllScore>
  </User>
  <User ID="User86" UserName="seanTW">
    <Team>Taiwan Team</Team>
    <Country>FRANCE</Country>
    <Project>World Community Grid</Project>
    <RegDate>2003/5/6</RegDate>
    <AvgScore>454.499</AvgScore>
    <AllScore>1801375</AllScore>
  </User>
  <User ID="User87" UserName="Paul_Woods_([H]ardOCP)">
    <Team>PitCrew @ PCPitStop</Team>
    <Country>SPAIN</Country>
    <Project>Sudoku project</Project>
    <RegDate>2001/10/6</RegDate>
    <AvgScore>72.787</AvgScore>
    <AllScore>5167486</AllScore>
  </User>
  <User ID="User88" UserName="XtremeGamer">
    <Team>p2p-community</Team>
    <Country>VENEZUELA</Country>
    <Project>Climate Prediction</Project>
    <RegDate>2004/3/28</RegDate>
    <AvgScore>65.048</AvgScore>
    <AllScore>3374003</AllScore>
  </User>
  <User ID="User89" UserName="Beauceron">
    <Team>2ch@PS3</Team>
    <Country>SWEDEN</Country>
    <Project>World Community Grid</Project>
    <RegDate>2000/11/9</RegDate>
    <AvgScore>219.093</AvgScore>
    <AllScore>4006449</AllScore>
  </User>
  <User ID="User90" UserName="Ivoch">
    <Team>China Folding@Home Power</Team>
    <Country>SPAIN</Country>
    <Project>Rosetta@Home</Project>
    <RegDate>2001/9/16</RegDate>
    <AvgScore>857.514</AvgScore>
    <AllScore>5042539</AllScore>
  </User>
  <User ID="User91" UserName="Krost">
    <Team>PC Perspective Folding Frogs (734)</Team>
    <Country>UNITED STATES</Country>
    <Project>Rosetta@Home</Project>
    <RegDate>2002/5/8</RegDate>
    <AvgScore>535.977</AvgScore>
    <AllScore>2017264</AllScore>
  </User>
  <User ID="User92" UserName="Curisco">
    <Team>ClubLexus</Team>
    <Country>THAILAND</Country>
    <Project>World Community Grid</Project>
    <RegDate>1999/5/3</RegDate>
    <AvgScore>186.879</AvgScore>
    <AllScore>9024193</AllScore>
  </User>
  <User ID="User93" UserName="NEO-BAHAMUT-">
    <Team>HKEPC</Team>
    <Country>NORWAY</Country>
    <Project>RALPH@Home</Project>
    <RegDate>2005/1/14</RegDate>
    <AvgScore>339.591</AvgScore>
    <AllScore>4677423</AllScore>
  </User>
  <User ID="User94" UserName="RDKamikaze">
    <Team>Team Hack-a-Day</Team>
    <Country>UNITED KINGDOM</Country>
    <Project>Enigma@Home</Project>
    <RegDate>2006/9/21</RegDate>
    <AvgScore>728.376</AvgScore>
    <AllScore>7181641</AllScore>
  </User>
  <User ID="User95" UserName="Laptop">
    <Team>Team Icrontic.com</Team>
    <Country>GERMANY</Country>
    <Project>Einstein@Home</Project>
    <RegDate>2007/9/21</RegDate>
    <AvgScore>84.331</AvgScore>
    <AllScore>5549038</AllScore>
  </User>
  <User ID="User96" UserName="teku0215">
    <Team>MicroMart-UK</Team>
    <Country>RUSSIAN FEDERATION</Country>
    <Project>ABC@home</Project>
    <RegDate>2004/1/24</RegDate>
    <AvgScore>908.962</AvgScore>
    <AllScore>9738194</AllScore>
  </User>
  <User ID="User97" UserName="Soapy_Sam">
    <Team>Macrumors.com - Team Folding</Team>
    <Country>IRELAND</Country>
    <Project>ABC@home</Project>
    <RegDate>1999/1/29</RegDate>
    <AvgScore>108.326</AvgScore>
    <AllScore>8614240</AllScore>
  </User>
  <User ID="User98" UserName="Will">
    <Team>PS3Forums.com</Team>
    <Country>UNITED STATES</Country>
    <Project>Climate Prediction</Project>
    <RegDate>2002/5/21</RegDate>
    <AvgScore>811.350</AvgScore>
    <AllScore>7613721</AllScore>
  </User>
  <User ID="User99" UserName="NightRider">
    <Team>XCPUs.com</Team>
    <Country>GERMANY</Country>
    <Project>World Community Grid</Project>
    <RegDate>2009/7/16</RegDate>
    <AvgScore>831.863</AvgScore>
    <AllScore>4856308</AllScore>
  </User>
  <User ID="User100" UserName="Gobit">
    <Team>Maximum PC Magazine</Team>
    <Country>GERMANY</Country>
    <Project>Einstein@Home</Project>
    <RegDate>2004/9/22</RegDate>
    <AvgScore>804.238</AvgScore>
    <AllScore>853001</AllScore>
  </User>
  <User ID="User101" UserName="RDL17">
    <Team>TSC! Russia</Team>
    <Country>JAPAN</Country>
    <Project>Collatz Conjecture</Project>
    <RegDate>2001/8/26</RegDate>
    <AvgScore>763.571</AvgScore>
    <AllScore>1519519</AllScore>
  </User>
  <User ID="User102" UserName="mirouf">
    <Team>OcUK</Team>
    <Country>FINLAND</Country>
    <Project>Cosmology@Home</Project>
    <RegDate>2002/9/10</RegDate>
    <AvgScore>38.469</AvgScore>
    <AllScore>5251580</AllScore>
  </User>
  <User ID="User103" UserName="Twinkletoese">
    <Team>PlanetAMD64</Team>
    <Country>SLOVAKIA</Country>
    <Project>Genetic Life</Project>
    <RegDate>2004/4/18</RegDate>
    <AvgScore>972.144</AvgScore>
    <AllScore>9904097</AllScore>
  </User>
  <User ID="User104" UserName="google137820589538553">
    <Team>Team Lithuania</Team>
    <Country>POLAND</Country>
    <Project>LHC@Home</Project>
    <RegDate>2003/7/9</RegDate>
    <AvgScore>707.482</AvgScore>
    <AllScore>5748715</AllScore>
  </User>
  <User ID="User105" UserName="aking">
    <Team>Portugal@Folding</Team>
    <Country>FRANCE</Country>
    <Project>Rosetta@Home</Project>
    <RegDate>1999/2/11</RegDate>
    <AvgScore>985.531</AvgScore>
    <AllScore>3624583</AllScore>
  </User>
  <User ID="User106" UserName="google277615858634497">
    <Team>AMD Zone</Team>
    <Country>NEW ZEALAND</Country>
    <Project>PrimeGrid</Project>
    <RegDate>2009/6/7</RegDate>
    <AvgScore>914.125</AvgScore>
    <AllScore>8990797</AllScore>
  </User>
  <User ID="User107" UserName="bob_white">
    <Team>Team Lithuania</Team>
    <Country>HONG KONG</Country>
    <Project>World Community Grid</Project>
    <RegDate>2005/4/19</RegDate>
    <AvgScore>128.290</AvgScore>
    <AllScore>706154</AllScore>
  </User>
  <User ID="User108" UserName="Uncyclotron9xw">
    <Team>Overclockers Australia</Team>
    <Country>UNITED STATES</Country>
    <Project>AQUA@home</Project>
    <RegDate>2009/8/4</RegDate>
    <AvgScore>844.454</AvgScore>
    <AllScore>4446696</AllScore>
  </User>
  <User ID="User109" UserName="MoltenTesseract">
    <Team>Overclockers Australia</Team>
    <Country>NEW ZEALAND</Country>
    <Project>SETI@Home</Project>
    <RegDate>2009/7/30</RegDate>
    <AvgScore>610.649</AvgScore>
    <AllScore>1581777</AllScore>
  </User>
  <User ID="User110" UserName="dysfirkin">
    <Team>TSC! Russia</Team>
    <Country>SOUTH AFRICA</Country>
    <Project>ABC@home</Project>
    <RegDate>1999/7/19</RegDate>
    <AvgScore>987.505</AvgScore>
    <AllScore>114213</AllScore>
  </User>
  <User ID="User111" UserName="BigFat">
    <Team>The Folding Wolves</Team>
    <Country>UNITED STATES</Country>
    <Project>Spinhenge@home</Project>
    <RegDate>2006/10/10</RegDate>
    <AvgScore>905.977</AvgScore>
    <AllScore>9515584</AllScore>
  </User>
  <User ID="User112" UserName="billc">
    <Team>EOC Folding@Home Team</Team>
    <Country>UNITED STATES</Country>
    <Project>yoyo@home</Project>
    <RegDate>2008/9/4</RegDate>
    <AvgScore>590.048</AvgScore>
    <AllScore>7845577</AllScore>
  </User>
  <User ID="User113" UserName="Angelo_Loi">
    <Team>[H]ardOCP</Team>
    <Country>PHILIPPINES</Country>
    <Project>Collatz Conjecture</Project>
    <RegDate>2003/11/9</RegDate>
    <AvgScore>691.417</AvgScore>
    <AllScore>901064</AllScore>
  </User>
  <User ID="User114" UserName="Mobz">
    <Team>DSL Reports Team Helix</Team>
    <Country>BULGARIA</Country>
    <Project>RSA Lattice Siever (2.0)</Project>
    <RegDate>2001/5/14</RegDate>
    <AvgScore>594.471</AvgScore>
    <AllScore>2214664</AllScore>
  </User>
  <User ID="User115" UserName="IsBOF">
    <Team>Pleasuredome Community</Team>
    <Country>JAPAN</Country>
    <Project>SETI@Home Beta</Project>
    <RegDate>2006/9/7</RegDate>
    <AvgScore>79.678</AvgScore>
    <AllScore>9016805</AllScore>
  </User>
  <User ID="User116" UserName="HubbyRice">
    <Team>[H]ardOCP</Team>
    <Country>UNITED KINGDOM</Country>
    <Project>SIMAP</Project>
    <RegDate>2004/5/8</RegDate>
    <AvgScore>657.445</AvgScore>
    <AllScore>4693691</AllScore>